export const ALL_STORE_REQUEST = "ALL_STORE_REQUEST";
export const ALL_STORE_SUCCESS = "ALL_STORE_SUCCESS";
export const ALL_STORE_FAIL = "ALL_STORE_FAIL";

export const NEW_STORE_REQUEST = "NEW_STORE_REQUEST";
export const NEW_STORE_SUCCESS = "NEW_STORE_SUCCESS";
export const NEW_STORE_FAIL = "NEW_STORE_FAIL";
export const NEW_STORE_RESET = "NEW_STORE_RESET";

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";
export const UPDATE_STORE_RESET = "UPDATE_STORE_RESET";

export const STORE_DETAILS_REQUEST = "STORE_DETAILS_REQUEST";
export const STORE_DETAILS_SUCCESS = "STORE_DETAILS_SUCCESS";
export const STORE_DETAILS_FAIL = "STORE_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
